### ISSUE TITLE
example of postgres::tls::TlsHandshake

### ISSUE THREAD

**Issue by marti1125** [sfackler/rust-native-tls#38]
I am trying to use TlsMode::Require following the example https://docs.rs/postgres/0.14.1/postgres/
but the import doesn't exist use postgres::tls::native_tls::NativeTls;
old version it has http://sfackler.github.io/rust-postgres/doc/v0.13.2/postgres/?search=postgres%3A%3Atls

**Comment by sfackler** [comment]
You'll need to enable the `with-native-tls` Cargo feature.

**Comment by marti1125** [comment]
how to =/ [features]
features = ["with-native-tls"]

**Comment by sfackler** [comment]
```toml
[dependencies]
postgres = { version = "0.14", features = ["with-native-tls"] }
```
