### ISSUE TITLE
Unable to build git master on Linux (OpenSSL binding)

### ISSUE THREAD

**Issue by johnthagen** [sfackler/rust-native-tls#93]
On a clean Ubuntu 16.04.4 32-bit (the problem seems to happen on 64-bit Linux as well) VM I installed:

```bash
$ sudo apt install gcc pkg-config libssl-dev
```

Project:

```toml
# Cargo.toml
...
[dependencies]
native-tls = { git = "https://github.com/sfackler/rust-native-tls" }
```

`main.rs` is populated with the example client from the `native-tls` README.

The build cannot find `SslOptions::NO_SSL_V2` (Did you mean `NO_SSLV2`) or `SslOptions:NO_TLSV1_0` (Did you mean `NO_TLSV1_1`)?

OpenSSL version:

```bash
$ openssl version
OpenSSL 1.0.2g  1 Mar 2016
```

Confirmed the problem exists on stable Rust 1.26.0 and nightly 2018-05-25.
